# Check for sudo vulnerability aka Baron Samedit aka CVE-2021-3156

# Playbook usage: 
# anisble-playbook check-sudo-vuln-CVE-2021-3156.yml-e target=yourHostGroup

---
- hosts: "{{ target }}"
  vars:
    unpatched_output: !unsafe 'sudoedit: /: not a regular file' 
  tasks:

    - name: check sudoedit
      become: true
      shell: 
        cmd: /usr/bin/sudoedit -s /
        executable: /usr/bin/bash
      register: sudoedit_check
      ignore_errors: yes
      failed_when: false

    - name: Show Vulnerable Hosts
      debug:
       msg: "VULNERABLE: {{ inventory_hostname }}"
      when: sudoedit_check.stderr == unpatched_output