---

# Quick and dirty playbook to install latest sudo version to remediate CVE-2021-3156. 
# This playbook handles RHEL 7 and RHEL 5 hosts. 
# Assumes the RHEL 7 hosts can use RHEL repos normally.
# Assumes the RHEL 5 hosts are in a restricted vlan without internet access
# and the Ansible control host will need to push packages into the RHEL 5 vlan.

# Usage: 
# ansible-playbook patch-sudo-vuln-CVE-2021-3156.yml -e target=yourHostGroup

- hosts: "{{ target }}"
  vars:
    rhel5_32bit_rpm_url: "https://github.com/sudo-project/sudo/releases/download/SUDO_1_9_5p2/sudo-1.9.5-3.el5.i386.rpm"
    rhel5_64bit_rpm_url: "https://github.com/sudo-project/sudo/releases/download/SUDO_1_9_5p2/sudo-1.9.5-3.el5.x86_64.rpm"
    sudo_project_pgp_keys_url: "https://www.sudo.ws/dist/PGPKEYS"

  tasks:
  - name: Get RHEL 5 sudo files.
    get_url:
      url: "{{ item }}"
      dest: ./
    loop:
      - "{{ rhel5_32bit_rpm_url }}"
      - "{{ rhel5_64bit_rpm_url }}"
      - "{{ sudo_project_pgp_keys_url }}"
    delegate_to: 127.0.0.1
  
  - name: Install latest sudo on RHEL-7 hosts.
    block:
      - name: Ensure sudo at latest version.
        become: true
        yum:
          name: sudo
          state: latest
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

  - name: Install updated sudo on RHEL 5 hosts.
    block:
      - name: Copy RPM to remote host.
        become: true
        copy:
          src: "sudo-1.9.5-3.el5.{{ ansible_architecture }}.rpm"
          dest: /tmp/sudo-patch/

      - name: Copy pgp keys to remote host.
        become: true
        copy:
          src: PGPKEYS
          dest: /tmp/sudo-patch/

      - name: Import rpm pgp keys.
        become: true
        shell:
          chdir: /tmp/sudo-patch/
          cmd: rpm --import PGPKEYS

      - name: Install RPM.
        become: true
        shell:
          chdir: /tmp/sudo-patch/
          cmd: yum localinstall --disablerepo=* ./sudo-*.rpm -y

      # Using shell command above rather than the yum module
      # since RHEL 5 has Python 2 and I don't want to deal 
      # with installing the Python 2 bindings for rpm now.
#     - name: Install RPM.
#       become: true
#       yum:
#         disablerepo: '*'
#         name: /tmp/sudo-patch/*.rpm
#         state: present

      - name: Remove temp install dir.
        become: true
        file:
          path: /tmp/sudo-patch/
          state: absent
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '5'
